### ISSUE TITLE
Can't compile.

### ISSUE THREAD

**Issue by Gryogor** [ravijo/ros_openpose#1]
After cloning  the ros_openpose repo and run catkin_make i receive this output:
Base path: /home/gryogor/catkin_ws
Source space: /home/gryogor/catkin_ws/src
Build space: /home/gryogor/catkin_ws/build
Devel space: /home/gryogor/catkin_ws/devel
Install space: /home/gryogor/catkin_ws/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/gryogor/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /home/gryogor/catkin_ws/devel;/opt/ros/kinetic
-- This workspace overlays: /home/gryogor/catkin_ws/devel;/opt/ros/kinetic
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: False
-- catkin 0.7.18
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 3 packages in topological order:
-- ~~  - realsense2_description
-- ~~  - ros_openpose
-- ~~  - realsense2_camera
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'realsense2_description'
-- ==> add_subdirectory(realsense-ros/realsense2_description)
-- +++ processing catkin package: 'ros_openpose'
-- ==> add_subdirectory(ros_openpose)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- ros_openpose: 4 messages, 0 services
-- +++ processing catkin package: 'realsense2_camera'
-- ==> add_subdirectory(realsense-ros/realsense2_camera)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Create Debug Build.
-- realsense2_camera: 2 messages, 0 services
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gryogor/catkin_ws/build
####
####
[  0%] Built target _ros_openpose_generate_messages_check_deps_Pixel
[  0%] Built target _ros_openpose_generate_messages_check_deps_Frame
[  0%] Built target _ros_openpose_generate_messages_check_deps_BodyPart
[  0%] Built target _ros_openpose_generate_messages_check_deps_Person
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_nodejs
Scanning dependencies of target testCameraReader
Scanning dependencies of target rosOpenpose
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_lisp
[  2%] Building CXX object ros_openpose/CMakeFiles/testCameraReader.dir/src/testCameraReader.cpp.o
[  2%] Built target _catkin_empty_exported_target
[  2%] Built target diagnostic_msgs_generate_messages_py
[  4%] Building CXX object ros_openpose/CMakeFiles/rosOpenpose.dir/src/rosOpenpose.cpp.o
[  4%] Built target sensor_msgs_generate_messages_lisp
[  4%] Built target roscpp_generate_messages_lisp
[  6%] Building CXX object ros_openpose/CMakeFiles/testCameraReader.dir/src/cameraReader.cpp.o
[  6%] Built target roscpp_generate_messages_nodejs
[  6%] Built target rosgraph_msgs_generate_messages_lisp
[  6%] Built target rosgraph_msgs_generate_messages_py
[  6%] Built target sensor_msgs_generate_messages_nodejs
[  6%] Built target sensor_msgs_generate_messages_eus
[  9%] Building CXX object ros_openpose/CMakeFiles/rosOpenpose.dir/src/cameraReader.cpp.o
/home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp: In member function ‘virtual sPtrVecSPtrDatum WUserInput::workProducer()’:
/home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:60:31: error: no match for ‘operator=’ (operand types are ‘op::Matrix’ and ‘const cv::Mat’)
         datumPtr->cvInputData = colorImage;
                               ^
In file included from /usr/local/include/openpose/core/array.hpp:7:0,
                 from /usr/local/include/openpose/core/common.hpp:10,
                 from /usr/local/include/openpose/3d/cameraParameterReader.hpp:4,
                 from /usr/local/include/openpose/3d/headers.hpp:5,
                 from /usr/local/include/openpose/headers.hpp:5,
                 from /home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:21:
/usr/local/include/openpose/core/matrix.hpp:95:18: note: candidate: op::Matrix& op::Matrix::operator=(const op::Matrix&)
     class OP_API Matrix
                  ^
/usr/local/include/openpose/core/matrix.hpp:95:18: note:   no known conversion for argument 1 from ‘const cv::Mat’ to ‘const op::Matrix&’
/usr/local/include/openpose/core/matrix.hpp:95:18: note: candidate: op::Matrix& op::Matrix::operator=(op::Matrix&&)
/usr/local/include/openpose/core/matrix.hpp:95:18: note:   no known conversion for argument 1 from ‘const cv::Mat’ to ‘op::Matrix&&’
/home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp: In function ‘void configureOpenPose(op::Wrapper&, const std::shared_ptr<ros_openpose::CameraReader>&, const ros::Publisher&, const string&)’:
/home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:187:5: error: ‘check’ is not a member of ‘op’
     op::check(0 <= FLAGS_logging_level && FLAGS_logging_level <= 255,
     ^
/home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:187:5: note: suggested alternative:
In file included from /opt/ros/kinetic/include/ros/ros.h:52:0,
                 from /home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:13:
/opt/ros/kinetic/include/ros/master.h:80:18: note:   ‘ros::master::check’
 ROSCPP_DECL bool check();
                  ^
/home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:198:78: error: invalid initialization of reference of type ‘const op::String&’ from expression of type ‘fLS::clstring {aka std::__cxx11::basic_string<char>}’
     const auto outputSize = op::flagsToPoint(FLAGS_output_resolution, "-1x-1");
                                                                              ^
In file included from /usr/local/include/openpose/utilities/headers.hpp:10:0,
                 from /usr/local/include/openpose/headers.hpp:44,
                 from /home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:21:
/usr/local/include/openpose/utilities/flagsToOpenPose.hpp:41:23: note: in passing argument 1 of ‘op::Point<int> op::flagsToPoint(const op::String&, const op::String&)’
     OP_API Point<int> flagsToPoint(const String& pointString, const String& pointExample = String("1280x720"));
                       ^
/home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:201:78: error: invalid initialization of reference of type ‘const op::String&’ from expression of type ‘fLS::clstring {aka std::__cxx11::basic_string<char>}’
     const auto netInputSize = op::flagsToPoint(FLAGS_net_resolution, "-1x368");
                                                                              ^
In file included from /usr/local/include/openpose/utilities/headers.hpp:10:0,
                 from /usr/local/include/openpose/headers.hpp:44,
                 from /home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:21:
/usr/local/include/openpose/utilities/flagsToOpenPose.hpp:41:23: note: in passing argument 1 of ‘op::Point<int> op::flagsToPoint(const op::String&, const op::String&)’
     OP_API Point<int> flagsToPoint(const String& pointString, const String& pointExample = String("1280x720"));
                       ^
/home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:204:106: error: invalid initialization of reference of type ‘const op::String&’ from expression of type ‘fLS::clstring {aka std::__cxx11::basic_string<char>}’
     const auto faceNetInputSize = op::flagsToPoint(FLAGS_face_net_resolution, "368x368 (multiples of 16)");
                                                                                                          ^
In file included from /usr/local/include/openpose/utilities/headers.hpp:10:0,
                 from /usr/local/include/openpose/headers.hpp:44,
                 from /home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:21:
/usr/local/include/openpose/utilities/flagsToOpenPose.hpp:41:23: note: in passing argument 1 of ‘op::Point<int> op::flagsToPoint(const op::String&, const op::String&)’
     OP_API Point<int> flagsToPoint(const String& pointString, const String& pointExample = String("1280x720"));
                       ^
/home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:207:106: error: invalid initialization of reference of type ‘const op::String&’ from expression of type ‘fLS::clstring {aka std::__cxx11::basic_string<char>}’
     const auto handNetInputSize = op::flagsToPoint(FLAGS_hand_net_resolution, "368x368 (multiples of 16)");
                                                                                                          ^
In file included from /usr/local/include/openpose/utilities/headers.hpp:10:0,
                 from /usr/local/include/openpose/headers.hpp:44,
                 from /home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:21:
/usr/local/include/openpose/utilities/flagsToOpenPose.hpp:41:23: note: in passing argument 1 of ‘op::Point<int> op::flagsToPoint(const op::String&, const op::String&)’
     OP_API Point<int> flagsToPoint(const String& pointString, const String& pointExample = String("1280x720"));
                       ^
/home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:213:65: error: invalid initialization of reference of type ‘const op::String&’ from expression of type ‘fLS::clstring {aka std::__cxx11::basic_string<char>}’
     const auto poseModel = op::flagsToPoseModel(FLAGS_model_pose);
                                                                 ^
In file included from /usr/local/include/openpose/utilities/headers.hpp:10:0,
                 from /usr/local/include/openpose/headers.hpp:44,
                 from /home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:21:
/usr/local/include/openpose/utilities/flagsToOpenPose.hpp:15:22: note: in passing argument 1 of ‘op::PoseModel op::flagsToPoseModel(const op::String&)’
     OP_API PoseModel flagsToPoseModel(const String& poseModeString);
                      ^
/home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:278:70: error: no matching function for call to ‘op::WrapperStructPose::WrapperStructPose(<brace-enclosed initializer list>)’
                                                   enableGoogleLogging};
                                                                      ^
In file included from /usr/local/include/openpose/wrapper/wrapper.hpp:13:0,
                 from /usr/local/include/openpose/wrapper/headers.hpp:6,
                 from /usr/local/include/openpose/headers.hpp:47,
                 from /home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:21:
/usr/local/include/openpose/wrapper/wrapperStructPose.hpp:212:9: note: candidate: op::WrapperStructPose::WrapperStructPose(op::PoseMode, const op::Point<int>&, const op::Point<int>&, op::ScaleMode, int, int, int, float, op::RenderMode, op::PoseModel, bool, float, float, int, const op::String&, const std::vector<op::HeatMapType>&, op::ScaleMode, bool, float, int, bool, double, const op::String&, const op::String&, float, bool)
         WrapperStructPose(
         ^
/usr/local/include/openpose/wrapper/wrapperStructPose.hpp:212:9: note:   conversion of argument 2 would be ill-formed:
/usr/local/include/openpose/wrapper/wrapperStructPose.hpp:18:19: note: candidate: op::WrapperStructPose::WrapperStructPose(const op::WrapperStructPose&)
     struct OP_API WrapperStructPose
                   ^
/usr/local/include/openpose/wrapper/wrapperStructPose.hpp:18:19: note:   candidate expects 1 argument, 26 provided
/usr/local/include/openpose/wrapper/wrapperStructPose.hpp:18:19: note: candidate: op::WrapperStructPose::WrapperStructPose(op::WrapperStructPose&&)
/usr/local/include/openpose/wrapper/wrapperStructPose.hpp:18:19: note:   candidate expects 1 argument, 26 provided
/home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:290:85: error: no matching function for call to ‘op::WrapperStructFace::WrapperStructFace(<brace-enclosed initializer list>)’
                                                   (float)FLAGS_face_render_threshold};
                                                                                     ^
In file included from /usr/local/include/openpose/wrapper/wrapper.hpp:8:0,
                 from /usr/local/include/openpose/wrapper/headers.hpp:6,
                 from /usr/local/include/openpose/headers.hpp:47,
                 from /home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:21:
/usr/local/include/openpose/wrapper/wrapperStructFace.hpp:69:9: note: candidate: op::WrapperStructFace::WrapperStructFace(bool, op::Detector, const op::Point<int>&, op::RenderMode, float, float, float)
         WrapperStructFace(
         ^
/usr/local/include/openpose/wrapper/wrapperStructFace.hpp:69:9: note:   conversion of argument 3 would be ill-formed:
/usr/local/include/openpose/wrapper/wrapperStructFace.hpp:16:19: note: candidate: op::WrapperStructFace::WrapperStructFace(const op::WrapperStructFace&)
     struct OP_API WrapperStructFace
                   ^
/usr/local/include/openpose/wrapper/wrapperStructFace.hpp:16:19: note:   candidate expects 1 argument, 7 provided
/usr/local/include/openpose/wrapper/wrapperStructFace.hpp:16:19: note: candidate: op::WrapperStructFace::WrapperStructFace(op::WrapperStructFace&&)
/usr/local/include/openpose/wrapper/wrapperStructFace.hpp:16:19: note:   candidate expects 1 argument, 7 provided
/home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:304:85: error: no matching function for call to ‘op::WrapperStructHand::WrapperStructHand(<brace-enclosed initializer list>)’
                                                   (float)FLAGS_hand_render_threshold};
                                                                                     ^
In file included from /usr/local/include/openpose/wrapper/wrapper.hpp:10:0,
                 from /usr/local/include/openpose/wrapper/headers.hpp:6,
                 from /usr/local/include/openpose/headers.hpp:47,
                 from /home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:21:
/usr/local/include/openpose/wrapper/wrapperStructHand.hpp:88:9: note: candidate: op::WrapperStructHand::WrapperStructHand(bool, op::Detector, const op::Point<int>&, int, float, op::RenderMode, float, float, float)
         WrapperStructHand(
         ^
/usr/local/include/openpose/wrapper/wrapperStructHand.hpp:88:9: note:   conversion of argument 3 would be ill-formed:
/usr/local/include/openpose/wrapper/wrapperStructHand.hpp:16:19: note: candidate: op::WrapperStructHand::WrapperStructHand(const op::WrapperStructHand&)
     struct OP_API WrapperStructHand
                   ^
/usr/local/include/openpose/wrapper/wrapperStructHand.hpp:16:19: note:   candidate expects 1 argument, 9 provided
/usr/local/include/openpose/wrapper/wrapperStructHand.hpp:16:19: note: candidate: op::WrapperStructHand::WrapperStructHand(op::WrapperStructHand&&)
/usr/local/include/openpose/wrapper/wrapperStructHand.hpp:16:19: note:   candidate expects 1 argument, 9 provided
/home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:334:69: error: no matching function for call to ‘op::WrapperStructOutput::WrapperStructOutput(<brace-enclosed initializer list>)’
                                                       FLAGS_udp_port};
                                                                     ^
In file included from /usr/local/include/openpose/wrapper/wrapper.hpp:12:0,
                 from /usr/local/include/openpose/wrapper/headers.hpp:6,
                 from /usr/local/include/openpose/headers.hpp:47,
                 from /home/gryogor/catkin_ws/src/ros_openpose/src/rosOpenpose.cpp:21:
/usr/local/include/openpose/wrapper/wrapperStructOutput.hpp:150:9: note: candidate: op::WrapperStructOutput::WrapperStructOutput(double, const op::String&, op::DataFormat, const op::String&, const op::String&, int, int, const op::String&, const op::String&, const op::String&, double, bool, const op::String&, const op::String&, const op::String&, const op::String&, const op::String&, const op::String&, const op::String&)
         WrapperStructOutput(
         ^
/usr/local/include/openpose/wrapper/wrapperStructOutput.hpp:150:9: note:   no known conversion for argument 2 from ‘fLS::clstring {aka std::__cxx11::basic_string<char>}’ to ‘const op::String&’
/usr/local/include/openpose/wrapper/wrapperStructOutput.hpp:13:19: note: candidate: op::WrapperStructOutput::WrapperStructOutput(const op::WrapperStructOutput&)
     struct OP_API WrapperStructOutput
                   ^
/usr/local/include/openpose/wrapper/wrapperStructOutput.hpp:13:19: note:   candidate expects 1 argument, 19 provided
/usr/local/include/openpose/wrapper/wrapperStructOutput.hpp:13:19: note: candidate: op::WrapperStructOutput::WrapperStructOutput(op::WrapperStructOutput&&)
/usr/local/include/openpose/wrapper/wrapperStructOutput.hpp:13:19: note:   candidate expects 1 argument, 19 provided
[  9%] Built target rosgraph_msgs_generate_messages_cpp
[  9%] Built target rosgraph_msgs_generate_messages_nodejs
[  9%] Built target rosgraph_msgs_generate_messages_eus
[  9%] Built target roscpp_generate_messages_py
[  9%] Built target sensor_msgs_generate_messages_py
[  9%] Built target roscpp_generate_messages_eus
[  9%] Built target sensor_msgs_generate_messages_cpp
[  9%] Built target roscpp_generate_messages_cpp
[  9%] Built target _realsense2_camera_generate_messages_check_deps_Extrinsics
[  9%] Built target _realsense2_camera_generate_messages_check_deps_IMUInfo
[  9%] Built target tf_generate_messages_cpp
ros_openpose/CMakeFiles/rosOpenpose.dir/build.make:62: recipe for target 'ros_openpose/CMakeFiles/rosOpenpose.dir/src/rosOpenpose.cpp.o' failed
make[2]: *** [ros_openpose/CMakeFiles/rosOpenpose.dir/src/rosOpenpose.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  9%] Built target actionlib_generate_messages_eus
[  9%] Built target dynamic_reconfigure_generate_messages_py
[  9%] Built target nodelet_generate_messages_nodejs
[  9%] Built target nav_msgs_generate_messages_lisp
[  9%] Built target bond_generate_messages_lisp
[  9%] Built target nodelet_generate_messages_cpp
[  9%] Built target nodelet_generate_messages_lisp
[  9%] Built target bond_generate_messages_cpp
[  9%] Built target tf2_msgs_generate_messages_eus
[  9%] Built target nodelet_generate_messages_py
[  9%] Built target nav_msgs_generate_messages_cpp
[  9%] Built target dynamic_reconfigure_generate_messages_nodejs
[  9%] Built target nav_msgs_generate_messages_eus
[  9%] Built target nav_msgs_generate_messages_py
[  9%] Built target tf2_msgs_generate_messages_py
[  9%] Built target actionlib_msgs_generate_messages_nodejs
[  9%] Built target actionlib_generate_messages_cpp
[  9%] Built target tf_generate_messages_eus
[  9%] Built target bond_generate_messages_py
[  9%] Built target dynamic_reconfigure_generate_messages_cpp
[  9%] Built target diagnostic_msgs_generate_messages_eus
[  9%] Built target actionlib_msgs_generate_messages_lisp
[  9%] Built target nav_msgs_generate_messages_nodejs
[  9%] Built target actionlib_generate_messages_py
[  9%] Built target bond_generate_messages_nodejs
[  9%] Built target actionlib_msgs_generate_messages_py
[  9%] Built target nodelet_generate_messages_eus
[  9%] Built target tf2_msgs_generate_messages_nodejs
[  9%] Built target dynamic_reconfigure_gencfg
[  9%] Built target tf_generate_messages_nodejs
[  9%] Built target diagnostic_msgs_generate_messages_cpp
[  9%] Built target tf_generate_messages_py
[  9%] Built target actionlib_generate_messages_lisp
[  9%] Built target actionlib_msgs_generate_messages_eus
[  9%] Built target actionlib_msgs_generate_messages_cpp
[  9%] Built target actionlib_generate_messages_nodejs
[  9%] Built target tf2_msgs_generate_messages_cpp
[  9%] Built target tf2_msgs_generate_messages_lisp
[  9%] Built target dynamic_reconfigure_generate_messages_eus
[  9%] Built target dynamic_reconfigure_generate_messages_lisp
[  9%] Built target bond_generate_messages_eus
[  9%] Built target diagnostic_msgs_generate_messages_lisp
[  9%] Built target diagnostic_msgs_generate_messages_nodejs
[  9%] Built target tf_generate_messages_lisp
[ 13%] Built target realsense2_camera_generate_messages_nodejs
[ 18%] Built target realsense2_camera_generate_messages_lisp
[ 25%] Built target realsense2_camera_generate_messages_eus
[ 31%] Built target realsense2_camera_generate_messages_py
[ 34%] Generating Python from MSG ros_openpose/BodyPart
[ 36%] Generating C++ code from ros_openpose/BodyPart.msg
[ 38%] Generating Python from MSG ros_openpose/Pixel
[ 40%] Generating C++ code from ros_openpose/Pixel.msg
[ 43%] Generating Python from MSG ros_openpose/Person
[ 45%] Generating C++ code from ros_openpose/Person.msg
[ 47%] Generating Python from MSG ros_openpose/Frame
[ 50%] Generating C++ code from ros_openpose/Frame.msg
[ 52%] Generating Python msg __init__.py for ros_openpose
[ 52%] Built target ros_openpose_generate_messages_cpp
[ 54%] Generating EusLisp code from ros_openpose/BodyPart.msg
[ 54%] Built target ros_openpose_generate_messages_py
[ 56%] Generating Javascript code from ros_openpose/BodyPart.msg
[ 59%] Generating EusLisp code from ros_openpose/Pixel.msg
[ 61%] Generating Javascript code from ros_openpose/Pixel.msg
[ 63%] Generating EusLisp code from ros_openpose/Person.msg
[ 65%] Generating Javascript code from ros_openpose/Person.msg
[ 68%] Generating EusLisp code from ros_openpose/Frame.msg
[ 70%] Generating Javascript code from ros_openpose/Frame.msg
[ 72%] Built target ros_openpose_generate_messages_eus
[ 72%] Built target ros_openpose_generate_messages_nodejs
[ 75%] Generating Lisp code from ros_openpose/BodyPart.msg
[ 79%] Built target realsense2_camera_generate_messages_cpp
[ 81%] Generating Lisp code from ros_openpose/Pixel.msg
[ 90%] Built target realsense2_camera
[ 90%] Built target realsense2_camera_generate_messages
[ 93%] Generating Lisp code from ros_openpose/Person.msg
[ 95%] Generating Lisp code from ros_openpose/Frame.msg
[ 95%] Built target ros_openpose_generate_messages_lisp
[ 95%] Built target ros_openpose_generate_messages
[ 97%] Linking CXX executable /home/gryogor/catkin_ws/devel/lib/ros_openpose/testCameraReader
CMakeFiles/Makefile2:1593: recipe for target 'ros_openpose/CMakeFiles/rosOpenpose.dir/all' failed
make[1]: *** [ros_openpose/CMakeFiles/rosOpenpose.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 97%] Built target testCameraReader
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

Does anyone know how to fix it?

**Comment by ravijo** [comment]
Hi @Gryogor 

I quickly looked at the error and found the following-
```
error: no match for ‘operator=’ (operand types are ‘op::Matrix’ and ‘const cv::Mat’)
datumPtr->cvInputData = colorImage;
```
I highly doubt that you are using a really old version of OpenPose. Can you please install OpenPose version 1.5.1? _The latest version of OpenPose should also work fine._

**Comment by Gryogor** [comment]
Thank you for the answer. I will try it. But how does your wrapper checks, which openpose to choose? Because I have 2 versions installed in different folders.

**Comment by ravijo** [comment]
> how does your wrapper checks, which openpose to choose? 

It uses `find_package` as shown below:

https://github.com/ravijo/ros_openpose/blob/709b96287daab9c429397d4278d22bee64fb2763/CMakeLists.txt#L25

> I have 2 versions installed in different folders.

As I said earlier, `find_package` must be able to located the latest OpenPose. To do that you must copy the compiled files into the system directories. You need to go inside the build directory of OpenPose and then execute the following command-

```
cd build/
sudo make install
```

You can look at the detailed instructions [here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/deployment.md#cmake-windows-ubuntu-and-mac).

**Comment by Gryogor** [comment]
Tried the most recent commit and version  1.5.1. Still gives the same error.

**Comment by Gryogor** [comment]
@ravijo 
Okey. I tried to install everything on completely clean ubuntu 16.04. This time everything worked without a problem. I am not sure what is the problem, but maybe older versions of installed openpose might be creating a problem.

**Comment by ravijo** [comment]
Hi @Gryogor 

> I tried to install everything on completely clean ubuntu 16.04. This time everything worked without a problem. 

I am glad that it worked. 

> maybe older versions of installed openpose might be creating a problem.

Yes, you are right. You can't have two versions of the same software installed system directories (globally). The command `sudo make install` basically overwrites your exiting OpenPose. Furthermore, I don't see any benefit of having multiple versions of OpenPose in one computer. 


Cheers
