### ISSUE TITLE
fatal error: ros_openpose/Frame.h: No such file or directory

### ISSUE THREAD

**Issue by LeviVasconcelos** [ravijo/ros_openpose#14]
ros_openpose/src/rosOpenpose.cpp:19:10: fatal error: ros_openpose/Frame.h: No such file or directory
 #include <ros_openpose/Frame.h>

Is this a missing file?

**Comment by LeviVasconcelos** [comment]
Hi, fixed it by adding this at line 88 of CMakeLists.txt:
add_dependencies(rosOpenpose ros_openpose_generate_messages_cpp)

**Comment by ravijo** [comment]
Thanks a lot, @LeviVasconcelos 

Normally, I re-execute the `catkin` command if such errors are shown, and then it disappears in the next run. However, it is good to have a fix for it. 

Added your suggestion in the main code. Please see [here](https://github.com/ravijo/ros_openpose/commit/583d09dfb82a3a393190825920ffa644255ff099)
