### ISSUE TITLE
Obtain 3D coordinates of each bone point

### ISSUE THREAD

**Issue by Michael-robo13** [ravijo/ros_openpose#16]
Hello,

Can I use openpose and realsense d435i to get the 3D coordinates of each bone point? Looking forward for your reply!

Best wishes!
Rogers

**Comment by ravijo** [comment]
Hello @Michael-robo13 

Sorry, I could not understand your question. What do you mean by "bone point"?

Let me explain to you what this package does. First, please [see this GIF image](https://github.com/ravijo/ros_openpose/blob/master/files/ros_openpose.gif). Now, please focus on the lower left window in this animation. You can notice that OpenPose has detected human skeleton points that are drawn using line strips in various colors. Later on, by using the depth information from the camera such as  RealSense D435, the package computes 3D coordinates for the real world.

Hope I cleared your question. Please revert back and open the issue if there is some confusion.
