### ISSUE TITLE
CMake Error - Ubuntu 18.04 Could not find a packae configuration file provided by OpenPose

### ISSUE THREAD

**Issue by AswinkarthikeyenAK** [ravijo/ros_openpose#18]
I tried to install openpose and then later installed ros_openpose.
I get the following error while doing catkin_make.

Please find the error msg below:-

CMake Error at ros_openpose/CMakeLists.txt:25 (find_package):
  By not providing "FindOpenPose.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenPose",
  but CMake did not find one.

  Could not find a package configuration file provided by "OpenPose" with any
  of the following names:

    OpenPoseConfig.cmake
    openpose-config.cmake

  Add the installation prefix of "OpenPose" to CMAKE_PREFIX_PATH or set
  "OpenPose_DIR" to a directory containing one of the above files.  If
  "OpenPose" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!

Can you kindly help me fix this please?

Thanks

**Comment by ravijo** [comment]
Hi @AswinkarthikeyenAK 

Are you using the latest version of OpenPose? I have tested it under Ubuntu 18.04 and found no issues. Can you please checkout v1.6.0 by executing the following command-

```
git checkout tags/v1.6.0
```

Next, another user recently reported a similar issue. Please check [here](https://github.com/ravijo/ros_openpose/issues/17#issuecomment-663484348) for the workaround suggested by that user.

I am closing the issue. However, feel free to open the issue if it persists.
