### ISSUE TITLE
Question about other cameras

### ISSUE THREAD

**Issue by Gryogor** [ravijo/ros_openpose#2]
Hello. Are you planning on implementing the support of ordinary RGB cameras for only 2D body image?

**Comment by ravijo** [comment]
Hi @Gryogor 

Thanks for reminding me. It is difficult to obtain and rely on depth information acquired by a single RGB camera. There are certain limitations. I do have plan to support (and provide pixel values only) an ordinary RGB camera. However, I am a bit busy preparing for IEEE IROS 2019.

Cheers

**Comment by Gryogor** [comment]
Ok. Thank you for the answer.

**Comment by ravijo** [comment]
@Gryogor: Thanks for this wonderful idea. I have added enhancement (new feature request) tag on this issue. I will be more than happy to look over it.

**Comment by Ceepert** [comment]
> @Gryogor: Thanks for this wonderful idea. I have added enhancement (new feature request) tag on this issue. I will be more than happy to look over it.

Did anything happen on this subject yet? I wanted to use a normal webcam with this wrapper

**Comment by ravijo** [comment]
Hi @Ceepert 

> Did anything happen on this subject yet? I wanted to use a normal webcam with this wrapper

Please check [here](https://github.com/ravijo/ros_openpose/issues/7#issuecomment-591995554).

**Comment by ravijo** [comment]
Hi @Gryogor

> Hello. Are you planning on implementing the support of ordinary RGB cameras for only 2D body image?

Yes. It is done. Please pull the recent changes from the repository. Now it supports any color camera such as webcam etc. See the [README.md](https://github.com/ravijo/ros_openpose/blob/master/README.md) for more details.
