### ISSUE TITLE
IndexError: index 720 is out of bounds for axis 0 with size 720

### ISSUE THREAD

**Issue by jyp0802** [ravijo/ros_openpose#45]
This is a very minor issue but there is an error in the code of `ros_openpose_synchronous.py`

on line 92:
original -> `if v <= depth.shape[0] and u <= depth.shape[1]:`

the **less than or equal to** should be changed to **less than** as:
fixed -> `if v < depth.shape[0] and u < depth.shape[1]:`

**Comment by ravijo** [comment]
@jyp0802 

Thank you so much for pointing this boundary condition. 

The following commit i.e., https://github.com/ravijo/ros_openpose/commit/13a5bdf24c30d561010d4eeb1b6eda2c47b04512 has implemented your suggestion.

Tagging @QuantuMope for reference.
