### ISSUE TITLE
use package offline

### ISSUE THREAD

**Issue by niccovezzi** [ravijo/ros_openpose#63]
hi
I would know if it's possible to use this package not in real time, for example with a registered video (like a file.avi).
Thanks in advantage.

**Comment by ravijo** [comment]
@niccovezzi 

Yes, you can use it offline with the help of the [rosbag](http://wiki.ros.org/rosbag). You need to record the topics with the rosbag and then you can use it offline.

Hope it helps!

**Comment by niccovezzi** [comment]
@ravijo 
Understood! Thanks for the quick response.

**Comment by ravijo** [comment]
Closing this issue because of no further comments. However, feel free to comment if the problem still exists.
