### ISSUE TITLE
Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by Enzosncf** [ravijo/ros_openpose#64]
Hello, 

I have an issue when is use this command : roslaunch ros_openpose run.launch camera:=nodepth

![Capture d’écran du 2022-06-01 16-27-37](https://user-images.githubusercontent.com/106229393/171428565-950c6dc6-15ac-4486-8d74-45a14f1559f3.png)

Do you have an idea ?

Best regards

**Comment by ravijo** [comment]
@Enzosncf 

The `CUDNN_STATUS_SUCCESS (4 vs. 0) CUDNN_STATUS_INTERNAL_ERROR` is certainly related to caffe framework. The error is reported by many over the internet:

- https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/2092
- https://github.com/BVLC/caffe/issues/6873
- https://forums.developer.nvidia.com/t/cudnn-conv-layer-cpp-53-check-failed-status-cudnn-status-success-4-vs-0-cudnn-status-internal-error/56243
- http://www.pittnuts.com/2015/07/notebook-of-caffe-development/
