### ISSUE TITLE
Cannot get it to work in the most standard configuration

### ISSUE THREAD

**Issue by ecl1p53** [ravijo/ros_openpose#68]
Hello Ravi,

I have been trying to get ros_openpose to run in different configurations (including different opencv versions, realsense2-camera from source etc.) for the last couple of days, but it seems I cannot get it to work.

My current configuration:
- Ubuntu 18.04
- ros-melodic-desktop
- ros-melodic-realsense2-camera & ros-melodic-realsense2-description with apt-get install ( small but known error: `WARNING [140594826397440] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11)` 
- openpose 1.7 from source (that works on the demo video)
- ros_openpose no errors compiling 

**Do you use the (included) ros-melodic-cv-bridge?  Or do I need to build it from source?**

I did set the folder path as per your instructions:
`  
  <arg name="openpose_args" value="--model_folder /home/installs/openpose/models/" />`

But when running it, the Openpose 1.7 screen gives an error and does nothing.
When I terminate:
```
^C[rviz-6] killing on exit
[camera/realsense2_camera-5] killing on exit
[camera/realsense2_camera_manager-4] killing on exit
[echo-3] killing on exit
[visualizer-2] killing on exit
[rosOpenpose-1] killing on exit

Error occurred on a thread. OpenPose closed all its threads and then propagated the error to the main thread. Error description:

Prototxt file not found: /home/installs/openpose/models/pose/body_25/pose_deploy.prototxt.
Possible causes:
	1. Not downloading the OpenPose trained models.
	2. Not running OpenPose from the root directory (i.e., where the `model` folder is located, but do not move the `model` folder!). E.g.,
		Right example for the Windows portable binary: `cd {OpenPose_root_path}; bin/openpose.exe`
		Wrong example for the Windows portable binary: `cd {OpenPose_root_path}/bin; openpose.exe`
	3. Using paths with spaces.

Coming from:
- /home/camp/Installs/openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():61
- /home/camp/Installs/openpose/src/openpose/net/netCaffe.cpp:ImplNetCaffe():97
- /home/camp/Installs/openpose/src/openpose/pose/poseExtractorCaffe.cpp:addCaffeNetOnThread():106
- /home/camp/Installs/openpose/src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():196
- /home/camp/Installs/openpose/src/openpose/pose/poseExtractorNet.cpp:initializationOnThread():102
- /home/camp/Installs/openpose/src/openpose/pose/poseExtractor.cpp:initializationOnThread():34
- /home/camp/Installs/openpose/include/openpose/pose/wPoseExtractor.hpp:initializationOnThread():57
- /home/camp/Installs/openpose/include/openpose/thread/worker.hpp:initializationOnThreadNoException():77
- [All threads closed and control returned to main thread]
- /home/camp/Installs/openpose/src/openpose/utilities/errorAndLog.cpp:checkWorkerErrors():280
- /home/camp/Installs/openpose/include/openpose/thread/threadManager.hpp:stop():243
- /home/camp/Installs/openpose/include/openpose/wrapper/wrapper.hpp:stop():455
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**I suspect that it has something to do with cv_bridge or that something is just going wrong with the "--model_folder" (is there another place to set it?)**
**Any help/tips would be greatly appreciated.**
ecl1p53

**Comment by ravijo** [comment]
@ecl1p53 

Thanks for creating this issue. Let me answer your points one by one:

> Do you use the (included) ros-melodic-cv-bridge? Or do I need to build it from source?

The ros_openpose uses the standard cv-bridge shipped along with ROS binaries. However, you are free to build the cv-bridge from the source but make sure it works with your ROS.

>  <arg name="openpose_args" value="--model_folder /home/installs/openpose/models/" />
> Prototxt file not found: /home/installs/openpose/models/pose/body_25/pose_deploy.prototxt.

You need to set the model path correctly. Please see below:

- Current path: /home/installs/openpose/models/
- Correct path: /home/camp/installs/openpose/models/

Cheers!

**Comment by ravijo** [comment]
Closing this issue because of no further comments. However, feel free to comment if the problem still exists.
