### ISSUE TITLE
Hand skeleton error

### ISSUE THREAD

**Issue by igurucr** [ravijo/ros_openpose#75]
Hi thank you for your code we were able to get it working with azure kinect and we are getting the body skeleton in RVIZ , now we want to get skeleton for the hands as well and we have passed skeleton_hands=true as an argument but We are unable to get the skeleton of hands. Whenever we try to do it, it's throwing an error. 
![Error Hands](https://user-images.githubusercontent.com/117928180/201137885-24c5db50-b329-404d-9e48-fd01fe0347d3.png)
@ravijo

**Comment by ravijo** [comment]
@igurucr 

Thank you very much for creating this issue. Please look at the following snippet:

https://github.com/ravijo/ros_openpose/blob/afecab60b39ea74a0673088589a377df49c5526e/launch/run.launch#L27-L28

The argument `skeleton_hands` enables visualization of the hands of the skeleton. To enable hand tracking, you need to pass `--hand` as OpenPose command line argument. May I request to check [Configuration#2](https://github.com/ravijo/ros_openpose#configuration)?

Please let me know if the issue persists.

Cheers

**Comment by igurucr** [comment]
@ravijo 

 Thank you for the response. It's working for the hand detection now, but the output seems to be a bit different as its giving negative values. Can you please elaborate regarding the output? 
![Hand Detection Data Output_1](https://user-images.githubusercontent.com/117928180/201546271-b7b26833-53da-4c7c-81f4-9350780d9dae.png)

**Comment by ravijo** [comment]
@igurucr 

> its giving negative values.

It is difficult to say if this is a problem. These values depend on the "Fixed Frame" inside RViz. Please check the frame once and let me know if it makes sense.

**Comment by ravijo** [comment]
Closing this issue as no further comments were received. Feel free to comment if the problem still exists.
