### ISSUE TITLE
Net Resolution

### ISSUE THREAD

**Issue by mobeeniqbal101** [ravijo/ros_openpose#76]
Hi how can I change the net resolution of my azure kinect in openpose using your wrapper to avoid the out of memory issue for my graphics card ?

**Comment by ravijo** [comment]
@mobeeniqbal101 

Thank you for opening this issue. May I request you to check [faq#2](https://github.com/ravijo/ros_openpose#faq) pleaase?

Please let me know if the issue persists.

Cheers

**Comment by mobeeniqbal101** [comment]
Thank you for your prompt response.
