### ISSUE TITLE
Only Hand Poses

### ISSUE THREAD

**Issue by mobeeniqbal101** [ravijo/ros_openpose#77]
Dear, we want to do gesture recognition and require the hand poses (only), but openpose does not work on only hands and has to detect the complete body, is there a way we can suppress the body poses and only transmit the hand poses over the ROS message ?

**Comment by ravijo** [comment]
@mobeeniqbal101 

> is there a way we can suppress the body poses and only transmit the hand poses over the ROS message 

Yes, if you are receiving hand poses (+ other such as body etc.) from OpenPose. You can edit the source code to allow only hand pose over ROS messages. Please read below:

1. Please disable (remove or comment) the following line: https://github.com/ravijo/ros_openpose/blob/afecab60b39ea74a0673088589a377df49c5526e/scripts/ros_openpose_synchronous.py#L167
2. Please disable (remove or comment) the following block: https://github.com/ravijo/ros_openpose/blob/afecab60b39ea74a0673088589a377df49c5526e/scripts/ros_openpose_synchronous.py#L177-L187

Let me know if you face any problem, please.

Cheers!
