### ISSUE TITLE
Skeleton error in Rviz

### ISSUE THREAD

**Issue by igurucr** [ravijo/ros_openpose#78]
@ravijo Hello,
 I was just checking how the code works and I think I have made some changes, now I can get the output and pointcloud data but the skeleton is not clearly visible and we are getting the following error in Rviz. Can you please help me with this?

![Skeleton Errors](https://user-images.githubusercontent.com/117928180/202425724-235b0111-1a6e-4fc7-9608-539041625d38.png)

Thank you

**Comment by ravijo** [comment]
@igurucr 

It seems there are some empty points which are causing visualization problem. Can you please post the output of `rostopic echo -n 1 /frame`

**Comment by ravijo** [comment]
Closing this issue as no further comments were received. Feel free to comment if the problem still exists.
