### ISSUE TITLE
Cmake Error - Package Configuration File Not Found

### ISSUE THREAD

**Issue by mahu0926** [ravijo/ros_openpose#82]
I have installed OpenPose and then cloned the repository. When I tried to do catkin build, I am getting a cmake error that states: 
```
By not providing "FindOpenPose.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "OpenPose",
but CMake did not find one.
```
I added these lines to CMakeLists.txt:
```
set(OPENPOSE_DIR ~/openpose)
set(OPENPOSE_INCLUDE_DIRS ${OPENpOSE_DIR}/include)
set(OPENPOSE_LINK_LIBRARY ${OPENPOSE_DIR}/build/lib/libopenpose.so)

target_link_libraries(${PROJECT_NAME}_node 
${catkin_LIBRARIES}
${OpenCV_LIBS}
${OPENPOSE_LINK_LIBRARY}
${GFLAGS_LIBRARY}
${GLOG_LIBRARY}
)
```
Running with these added lines did not change anything and I am still receiving the same error. Do you have any suggestions on what to do to fix this?

**Comment by ravijo** [comment]
Closing this issue as no further comments were received. Feel free to comment if the problem still exists.
