### ISSUE TITLE
Input the Wrapper a recorded Azure Kinect Video

### ISSUE THREAD

**Issue by mobeeniqbal101** [ravijo/ros_openpose#84]
Hi, is it possible to input your wrapper a recorded azure kinect video (recorded using azure kinect SDK) instead of the live feed ?

**Comment by ravijo** [comment]
@mobeeniqbal101 

I have not used Azure Kinect SDK extensively. However, if you can extract and publish images (camera info etc) from your recorded video, you can make it work.

**Comment by ravijo** [comment]
Closing this issue as no further comments were received. Feel free to comment if the problem still exists.
