### ISSUE TITLE
Need to detect only one person in the frame

### ISSUE THREAD

**Issue by igurucr** [ravijo/ros_openpose#86]
Hello,

Is there any way to make the open-pose detect only one person(i.e., the first person it detects) in the frame even if there are multiple persons detected in the frame?

We are getting the error of multi-person detection even if there is only one person in the frame.

Thank you

**Comment by ravijo** [comment]
@igurucr 

Unfortunately, the tracking feature is not available in OpenPose.

BTW, it is better to look at their documentations/papers/GitHub issues etc for better suggestion.

Thanks

**Comment by ravijo** [comment]
Closing this issue as no further comments have been received. However, feel free to comment if the problem still exists.
