### ISSUE TITLE
Missing tags section

### ISSUE THREAD

**Issue by fzoric8** [ravijo/ros_openpose#87]
Hi @ravijo. 

I've used `ros_openpose` for the OpenPose 1.6.0 and it worked well. 

Now I've compiled OpenPose 1.7.0 which works fine as standalone software, however
I've noticed that git `tags` in repo are missing, especially one for succesful build of the OpenPose 1.7.0. 

Thank you for you help.

**Comment by fzoric8** [comment]
I've built master for the OpenPose 1.7.0 without CUDNN support and everything works fine. So I suppose they're not necessary for the successful build. 

Config: 
* Ubuntu 20.04 
* RTX 3060 
* CUDA 11.1

**Comment by ravijo** [comment]
@fzoric8 

Glad you made it work!

Cheers
