### ISSUE TITLE
Lunch file operation error

### ISSUE THREAD

**Issue by Parkeunseok** [ravijo/ros_openpose#89]
Hello, I'm a beginner in this field using your code.
The basic open pose works, but when you operate your launch file, you get the following error. Please solve this problem. I'm sending you a screenshot of the error and lunch file I came out with.
Thank you.

![openpose_error](https://github.com/ravijo/ros_openpose/assets/87689132/bd3c4018-f1ce-4604-8851-7ede7e6c8a5f)

This is the default open pose motion screen.
![openpose](https://github.com/ravijo/ros_openpose/assets/87689132/cb88e45e-aa5b-4673-9cab-b15edb3c725a)

![ggggg](https://github.com/ravijo/ros_openpose/assets/87689132/342dac05-9563-4bac-858f-aea5601400e9)

**Comment by ravijo** [comment]
Hello @Parkeunseok 

Thanks for reporting the issue. It seems that the error is coming from OpenPose installation.
```
error while loading shared libraries: libcaffe.so.1.0.0: cannot open shared object file: No such file or directory
```
 Please check [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/148) and set `LD_LIBRARY_PATH`. Also, please check the following commented lines: https://github.com/ravijo/ros_openpose/blob/21e6c3e23bd49340e04aee1341e894142d9f66e7/CMakeLists.txt#L82-L85

You may have to set `CAFFE_LIB_FOLDER` to the location of `libcaffe.so` file.

**Comment by Parkeunseok** [comment]
A new error has appeared. Can you solve this, too?
![new_error](https://github.com/ravijo/ros_openpose/assets/87689132/6390ce97-292b-4d9f-a30d-51875b049a46)

**Comment by ravijo** [comment]
It seems that the output topic, where you get the processed data is set incorrectly.

The easiest way to confirm my hypothesis is to add a print statement at line 23:
https://github.com/ravijo/ros_openpose/blob/21e6c3e23bd49340e04aee1341e894142d9f66e7/scripts/echo.py#L22-L24

```
    rospy.loginfo('frame_topic: %s' % frame_topic)
```

If so, then you need to set it. Probably you have modifed the launch files incorrectly.

**Comment by Parkeunseok** [comment]
What is the solution to this error??
![cuda_error](https://github.com/ravijo/ros_openpose/assets/87689132/2e4fa1eb-dd81-4715-80dc-6d2bba7488cd)

first computer
RAM : 16GB
CPU : 12th Gen Intel® Core™ i7-12700KF × 20 
GPU : NVIDIA GeForce RTX 3080 


second computer
RAM : 16GB
CPU : 9th Gen Intel® Core™ i7-9750H 
GPU : NVIDIA GeForce GTX 1660Ti

**Comment by ravijo** [comment]
The error shown in your screenshot complaints about insufficient memory in your graphic card.

There are various ways to deal with it. I suggest checking the documentation please

**Comment by ravijo** [comment]
Closing this issue as no further comments have been received. However, feel free to comment if the problem still exists.
