### ISSUE TITLE
ros_openpose with ZED2 camera

### ISSUE THREAD

**Issue by ruksen25** [ravijo/ros_openpose#9]
Hi ravijo

I am working on getting this package working with my ZED2 camera. 
I have copied the config_realsense. launch file and tried to adapt it to my camera. 
I also similarly copied and modified the rviz file. 

Currently, I seem to be able to obtain a skeleton, and I can visualise in Rviz. However, the visualisation appears all weird. I can visualise my point cloud just fine, but of course this has also not been through manipulation in your wrapper.  It is mainly the skeleton which is visualised weird. 
The scale of it does not match the point cloud (or vice versa) , and I even in some cases seem to have a deformed skeleton. 

My question to you is if you have some parameters or variables in any parts of your wrapper that you think might be associated with the problem. Or maybe asked in another way: Can you line out the parameters/variables in your code that you think I need to look at and adapt in order to make it work with a different depth camera? 

I greatly appreciate any input you have.

**Comment by ravijo** [comment]
Hi @ruksen25 

Thank you very much.

> I have copied the config_realsense. launch file and tried to adapt it to my camera.
> I also similarly copied and modified the rviz file.

Perfect, this is what I would suggest in the first place.

> Currently, I seem to be able to obtain a skeleton, and I can visualise in Rviz. However, the visualisation appears all weird. I can visualise my point cloud just fine, but of course this has also not been through manipulation in your wrapper. It is mainly the skeleton which is visualised weird.
> The scale of it does not match the point cloud (or vice versa) , and I even in some cases seem to have a deformed skeleton.
> 
> My question to you is if you have some parameters or variables in any parts of your wrapper that you think might be associated with the problem. Or maybe asked in another way: Can you line out the parameters/variables in your code that you think I need to look at and adapt in order to make it work with a different depth camera?

The visualization is done by python script `visualizer.py` which you can find inside `scripts` directory. The skeleton is defined by a combination of line strips. More preciously, the skeleton is decomposed into 3 line strips as following- 1) upper_body (from nose to hip), 2) hands  (from left-hand wrist to right-hand wrist), and 3) legs (from left foot toe to right foot toe). Each line segment has a width, which is set by the parameter `skeleton_line_width`. Please set it to a lower value if the lines are appearing huge. Check [here](https://github.com/ravijo/ros_openpose/blob/f8e56368444c95067aa467c178b1a032fff74d58/launch/run.launch#L37), please.

A similar question was asked previously, please go through it. Check [here](https://github.com/ravijo/ros_openpose/issues/5), please. You can find the discussion on the mentioned URL very useful.

_PS: If you can share a screenshot of the RVIZ window, we can discuss it better. You can email me the screenshot if privacy is concerned!_

Let me know if the problem persists.

**Comment by ruksen25** [comment]
@ravijo 
Thank you for your reply and recommendations. 
The lines are not too thick. 
I already looked at the issue you linked to, but there seem to be some fundamental differences between my and that issue. I also looked into my camera calibration following your recomendation, but the ZED2 camera comes with a very precise calibration from the factory which they do not recommend you re-calibrate as you most likely will get a less precise result. 
after inspecting the topics published by your wrapper I have noticed that the Z value in all the points in the frame messages is always either z: 0.0010000000475 or  z: 65.5350036621 (no other values have been published). This gives me the impression that something is wrong before the visualisation. Nonetheless I have a feeling that I have a two fold issue. I attach a few images from my visualisation. The observations I have done myself is that the it seems like all the lines meet in one point (which of course should not be the case).  Secondly, this point is not aligned with the point cloud.

If I may I have a few questions to the input you use from the realsense: 
is your depth map from the realsense in mm or m and how many bits is it? 
Also which resolution are your input images? - And should I give this as an argument to the wrapper somewhere?


Explanation of the images: 
One shows how it seems like a lot of the lines are contained in one point when you zoom in. 
One other shows how all lines seem to meet in one point with an offset from the point cloud.
The last show the general view where it also looks like the scale between the skeleton and the point cloud does not match. 

Thank you for taking the time. I appreciate your help.

![Screenshot from 2020-04-15 15-41-20](https://user-images.githubusercontent.com/15103639/79426868-17553880-7fc4-11ea-9e09-22c2bc1add7e.png)
![Screenshot from 2020-04-15 15-54-10](https://user-images.githubusercontent.com/15103639/79426947-2e942600-7fc4-11ea-8139-c8e6189284be.png)
![Screenshot from 2020-04-07 11-52-21](https://user-images.githubusercontent.com/15103639/79427122-71ee9480-7fc4-11ea-9de2-60fb90a65b33.png)

**Comment by ravijo** [comment]
Hi @ruksen25 

Thank you very much for the information. The following information is required from the camera-

```
<!-- rostopic to subscribe for color images -->
<arg name="color_topic" default="/camera/color/image_raw" />

<!-- rostopic to subscribe for depth images -->
<arg name="depth_topic" default="/camera/aligned_depth_to_color/image_raw" />

<!-- rostopic to subscribe for camera calibration parameters -->
<arg name="cam_info_topic" default="/camera/color/camera_info" />

<!-- frame id for point cloud and 3D skeleton data -->
<arg name="frame_id" default="camera_depth_optical_frame" />
```

The trick here is that depth images are aligned to the color images. Also depth and color are having the same dimension. In this way, each pixel from the color image can be mapped to corros[doing depth pixel at the same x, y location. The `cam_info_topic` is containing camera calibration parameters supplied by the manufacturer.

Please see `compute3DPoint` function [here](https://github.com/ravijo/ros_openpose/blob/f8e56368444c95067aa467c178b1a032fff74d58/include/ros_openpose/cameraReader.hpp#L111) to understand the 2D to 3D conversation.  

> is your depth map from the realsense in mm or m?

It is in mm. You can see [here](https://github.com/ravijo/ros_openpose/blob/f8e56368444c95067aa467c178b1a032fff74d58/include/ros_openpose/cameraReader.hpp#L130) I am converting mm into m (SI Units).

> how many bits is it?

16 Bits. See [here](https://github.com/ravijo/ros_openpose/blob/f8e56368444c95067aa467c178b1a032fff74d58/src/cameraReader.cpp#L72) `TYPE_16UC1` is used as image encoding.

> Also which resolution are your input images? 

I don't remember right now. However, you can find this information online. The topic `/camera/color/image_raw` is published by RealSense Camera D435 model. The trick is to have Depth and Color in the same size and aligned as well. If not aligned, the `compute3DPoint` function has to be rewritten.

> And should I give this as an argument to the wrapper somewhere?

No. Not required.

Let me know the progress, please.

**Comment by ruksen25** [comment]
Thank you very much for your help. I think I have it running now. 

Turns out I had to change a parameter in the ROS-ZED-camera node to get depth in mm. 
I had actually already tried this, but apparently it also changes the name of the depth topic which I was not aware of. When I set this parameter and passed the right topic name it worked! 

Again thank you for your time. And thank you for making this wrapper available.

**Comment by ravijo** [comment]
Hi @ruksen25 

Thank you very much. I am glad you made it work!

Since I have not used a ZED camera, I wasn't aware of its parameters. I am sorry for the inconvenience. The depth images are mostly stored in 16 Bit (Kinect also follows the same convention).

1. Meanwhile, can you please share the changes you have done to make it? 
1. For example, the `color_topic`, `depth_topic`, `cam_info_topic` and `frame_id`? 
1. How did you change the ROS-ZED-camera node to get depth in mm?
1. Are you using [this wrapper](https://github.com/stereolabs/zed-ros-wrapper) for your camera?

After receiving this information, I will update (and create `config_zed.launch`) the documentation of `ros_openpose`.

Looking forward to hearing from you.

**Comment by ruksen25** [comment]
No worries! I did not expect you to know about this problem. As I already thought I tried to make these changes I thought this was not the issue and that the problem was somewhere else in the interfacing with your code.  I knew that my questions were a bit out of your scope, but I thought you might have some inputs that could hint me towards the solution. I very much appreciate your efforts in helping me find a solution. 

I already was thinking about making my zed2 solution available and thought of creating a git side on my own with the modified files and instructions.  but maybe it is nicer to have everything together in your repository. 

Maybe I can write out a section describing the use of the zed camera and send you that and the files I have created (modified from yours), which you can then add to the repository?

**Comment by ravijo** [comment]
Hi @ruksen25 

> No worries! I did not expect you to know about this problem. As I already thought I tried to make these changes I thought this was not the issue and that the problem was somewhere else in the interfacing with your code. I knew that my questions were a bit out of your scope, but I thought you might have some inputs that could hint me towards the solution. I very much appreciate your efforts in helping me find a solution.

Thank you very much.

> Maybe I can write out a section describing the use of the zed camera and send you that and the files I have created (modified from yours), which you can then add to the repository?

Perfect. I agree!

**Comment by AswinkarthikeyenAK** [comment]
``Hi @ruksen25,
I am trying to use the zed2 for openpose. At the moment, I am able to launch openpose fine with 
roslaunch ros_openpose run.launch synchronous:=true camera:=zed2, however, there is no skeleton visible in RViz.

I changed the openni_depth_mode:    true   

While testing with the intel camera, it seems to be fine. Whereas testing the same with ZED2, I have trouble at the moment. 
Can you please let me some other toubleshooting methods to have this fixed?
Below you will find the terminal output. 

`
SUMMARY
========

PARAMETERS
 * /echo/pub_topic: /frame
 * /rosOpenpose/cam_info_topic: /zed2/zed_node/rg...
 * /rosOpenpose/color_topic: /zed2/zed_node/rg...
 * /rosOpenpose/depth_topic: /zed2/zed_node/de...
 * /rosOpenpose/frame_id: zed2_left_camera_...
 * /rosOpenpose/no_depth: False
 * /rosOpenpose/pub_topic: /frame
 * /rosOpenpose/py_openpose_path: /usr/local/python
 * /rosdistro: melodic
 * /rosversion: 1.15.14
 * /visualizer/frame_id: zed2_left_camera_...
 * /visualizer/id_text_offset: -0.05
 * /visualizer/id_text_size: 0.2
 * /visualizer/pub_topic: /frame
 * /visualizer/skeleton_hands: False
 * /visualizer/skeleton_line_width: 0.01
 * /zed2/zed2_description: <?xml version="1....
 * /zed2/zed_node/auto_exposure_gain: True
 * /zed2/zed_node/auto_whitebalance: True
 * /zed2/zed_node/brightness: 4
 * /zed2/zed_node/contrast: 4
 * /zed2/zed_node/depth/depth_downsample_factor: 1.0
 * /zed2/zed_node/depth/depth_stabilization: 1
 * /zed2/zed_node/depth/max_depth: 20.0
 * /zed2/zed_node/depth/min_depth: 0.5
 * /zed2/zed_node/depth/openni_depth_mode: True
 * /zed2/zed_node/depth/quality: 1
 * /zed2/zed_node/depth/sensing_mode: 0
 * /zed2/zed_node/depth_confidence: 50
 * /zed2/zed_node/depth_texture_conf: 100
 * /zed2/zed_node/exposure: 100
 * /zed2/zed_node/gain: 100
 * /zed2/zed_node/gamma: 8
 * /zed2/zed_node/general/base_frame: base_link
 * /zed2/zed_node/general/camera_flip: False
 * /zed2/zed_node/general/camera_model: zed2
 * /zed2/zed_node/general/camera_name: zed2
 * /zed2/zed_node/general/gpu_id: -1
 * /zed2/zed_node/general/grab_frame_rate: 30
 * /zed2/zed_node/general/resolution: 1
 * /zed2/zed_node/general/self_calib: True
 * /zed2/zed_node/general/serial_number: 0
 * /zed2/zed_node/general/svo_compression: 2
 * /zed2/zed_node/general/verbose: False
 * /zed2/zed_node/general/zed_id: 0
 * /zed2/zed_node/hue: 0
 * /zed2/zed_node/mapping/fused_pointcloud_freq: 1.0
 * /zed2/zed_node/mapping/mapping_enabled: False
 * /zed2/zed_node/mapping/max_mapping_range: -1
 * /zed2/zed_node/mapping/resolution: 0.05
 * /zed2/zed_node/object_detection/body_fitting: True
 * /zed2/zed_node/object_detection/confidence_threshold: 50
 * /zed2/zed_node/object_detection/max_range: 15.0
 * /zed2/zed_node/object_detection/mc_animal: True
 * /zed2/zed_node/object_detection/mc_bag: True
 * /zed2/zed_node/object_detection/mc_electronics: True
 * /zed2/zed_node/object_detection/mc_fruit_vegetable: True
 * /zed2/zed_node/object_detection/mc_people: True
 * /zed2/zed_node/object_detection/mc_vehicle: True
 * /zed2/zed_node/object_detection/model: 3
 * /zed2/zed_node/object_detection/object_tracking_enabled: True
 * /zed2/zed_node/object_detection/od_enabled: False
 * /zed2/zed_node/point_cloud_freq: 100.0
 * /zed2/zed_node/pos_tracking/area_memory: True
 * /zed2/zed_node/pos_tracking/area_memory_db_path: zed_area_memory.area
 * /zed2/zed_node/pos_tracking/fixed_z_value: 0.0
 * /zed2/zed_node/pos_tracking/floor_alignment: False
 * /zed2/zed_node/pos_tracking/imu_fusion: True
 * /zed2/zed_node/pos_tracking/init_odom_with_first_valid_pose: True
 * /zed2/zed_node/pos_tracking/initial_base_pose: [0.0, 0.0, 0.0, 0...
 * /zed2/zed_node/pos_tracking/map_frame: map
 * /zed2/zed_node/pos_tracking/odometry_frame: odom
 * /zed2/zed_node/pos_tracking/path_max_count: -1
 * /zed2/zed_node/pos_tracking/path_pub_rate: 2.0
 * /zed2/zed_node/pos_tracking/pos_tracking_enabled: True
 * /zed2/zed_node/pos_tracking/publish_map_tf: True
 * /zed2/zed_node/pos_tracking/publish_tf: True
 * /zed2/zed_node/pos_tracking/save_area_memory_db_on_exit: False
 * /zed2/zed_node/pos_tracking/two_d_mode: False
 * /zed2/zed_node/pub_frame_rate: 100.0
 * /zed2/zed_node/saturation: 4
 * /zed2/zed_node/sensors/publish_imu_tf: True
 * /zed2/zed_node/sensors/sensors_timestamp_sync: False
 * /zed2/zed_node/sharpness: 4
 * /zed2/zed_node/stream: 
 * /zed2/zed_node/svo_file: 
 * /zed2/zed_node/video/extrinsic_in_camera_frame: True
 * /zed2/zed_node/video/img_downsample_factor: 1.0
 * /zed2/zed_node/whitebalance_temperature: 42

NODES
  /
    echo (ros_openpose/echo.py)
    rosOpenpose (ros_openpose/ros_openpose_synchronous.py)
    visualizer (ros_openpose/visualizer.py)
  /zed2/
    zed2_state_publisher (robot_state_publisher/robot_state_publisher)
    zed_node (zed_wrapper/zed_wrapper_node)

auto-starting new master
process[master]: started with pid [30878]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 65bdeb4e-bb26-11ec-a4b2-30d042e19d22
process[rosout-1]: started with pid [30904]
started core service [/rosout]
process[rosOpenpose-2]: started with pid [30911]
process[visualizer-3]: started with pid [30912]
process[echo-4]: started with pid [30913]
process[zed2/zed2_state_publisher-5]: started with pid [30914]
process[zed2/zed_node-6]: started with pid [30915]
[ INFO] [1649853414.030469459]: Initializing nodelet with 16 worker threads.
[ INFO] [1649853414.038660660]: ********** Starting nodelet '/zed2/zed_node' **********
[ INFO] [1649853414.038711203]: SDK version : 3.7.1
[ INFO] [1649853414.038728687]: *** GENERAL PARAMETERS ***
[ INFO] [1649853414.038962950]:  * Camera Name			-> zed2
[ INFO] [1649853414.039241476]:  * Camera Resolution		-> HD1080
[ INFO] [1649853414.039504357]:  * Camera Grab Framerate	-> 30
[ INFO] [1649853414.039718298]:  * Gpu ID			-> -1
[ INFO] [1649853414.039908575]:  * Camera ID			-> -1
[ INFO] [1649853414.040092160]:  * Verbose			-> DISABLED
[ INFO] [1649853414.041362166]:  * Camera Flip			-> DISABLED
[ INFO] [1649853414.041742249]:  * Self calibration		-> ENABLED
[ INFO] [1649853414.042116860]:  * Camera Model by param	-> zed2
[ INFO] [1649853414.042163516]: *** VIDEO PARAMETERS ***
[ INFO] [1649853414.042393032]:  * Image resample factor	-> 1
[ INFO] [1649853414.042618959]:  * Extrinsic param. frame	-> X RIGHT - Y DOWN - Z FWD
[ INFO] [1649853414.042629775]: *** DEPTH PARAMETERS ***
[ INFO] [1649853414.042820876]:  * Depth quality		-> PERFORMANCE
[ INFO] [1649853414.042999852]:  * Depth Sensing mode		-> STANDARD
[ INFO] [1649853414.043172827]:  * OpenNI mode			-> ENABLED
[ INFO] [1649853414.043376831]:  * Depth Stabilization		-> ENABLED
[ INFO] [1649853414.043586766]:  * Minimum depth		-> 0.5 m
[ INFO] [1649853414.043789545]:  * Maximum depth		-> 20 m
[ INFO] [1649853414.043988552]:  * Depth resample factor	-> 1
[ INFO] [1649853414.044002488]: *** POSITIONAL TRACKING PARAMETERS ***
[ INFO] [1649853414.045079011]:  * Positional tracking		-> ENABLED
[ INFO] [1649853414.045365838]:  * Path rate			-> 2 Hz
[ INFO] [1649853414.045549630]:  * Path history size		-> 1
[ INFO] [1649853414.045962670]:  * Odometry DB path		-> /home/aswin/.ros/zed_area_memory.area
[ INFO] [1649853414.046337281]:  * Save Area Memory on closing	-> DISABLED
[ INFO] [1649853414.046703815]:  * Area Memory			-> ENABLED
[ INFO] [1649853414.047066247]:  * IMU Fusion			-> ENABLED
[ INFO] [1649853414.047448344]:  * Floor alignment		-> DISABLED
[ INFO] [1649853414.047828879]:  * Init Odometry with first valid pose data -> ENABLED
[ INFO] [1649853414.048406691]:  * Two D mode			-> DISABLED
[ INFO] [1649853414.049096356]: *** MAPPING PARAMETERS ***
[ INFO] [1649853414.049458418]:  * Mapping			-> DISABLED
[ INFO] [1649853414.049472120]: *** OBJECT DETECTION PARAMETERS ***
[ INFO] [1649853414.049828799]:  * Object Detection		-> DISABLED
[ INFO] [1649853414.049842023]: *** SENSORS PARAMETERS ***
[ INFO] [1649853414.050031583]:  * Sensors timestamp sync	-> DISABLED
[ INFO] [1649853414.050044320]: *** SVO PARAMETERS ***
[ INFO] [1649853414.050407160]:  * SVO input file: 		-> 
[ INFO] [1649853414.050604997]:  * SVO REC compression		-> H265 (HEVC)
[ INFO] [1649853414.050966444]: *** COORDINATE FRAMES ***
[ INFO] [1649853414.052018327]:  * map_frame			-> map
[ INFO] [1649853414.052033969]:  * odometry_frame		-> odom
[ INFO] [1649853414.052051779]:  * base_frame			-> base_link
[ INFO] [1649853414.052067658]:  * camera_frame			-> zed2_camera_center
[ INFO] [1649853414.052083323]:  * imu_link			-> zed2_imu_link
[ INFO] [1649853414.052099365]:  * left_camera_frame		-> zed2_left_camera_frame
[ INFO] [1649853414.052128537]:  * left_camera_optical_frame	-> zed2_left_camera_optical_frame
[ INFO] [1649853414.052165708]:  * right_camera_frame		-> zed2_right_camera_frame
[ INFO] [1649853414.052199995]:  * right_camera_optical_frame	-> zed2_right_camera_optical_frame
[ INFO] [1649853414.052291716]:  * depth_frame			-> zed2_left_camera_frame
[ INFO] [1649853414.052345392]:  * depth_optical_frame		-> zed2_left_camera_optical_frame
[ INFO] [1649853414.052366500]:  * disparity_frame		-> zed2_left_camera_frame
[ INFO] [1649853414.052408409]:  * disparity_optical_frame	-> zed2_left_camera_optical_frame
[ INFO] [1649853414.052448407]:  * confidence_frame		-> zed2_left_camera_frame
[ INFO] [1649853414.052493768]:  * confidence_optical_frame	-> zed2_left_camera_optical_frame
[ INFO] [1649853414.053277107]:  * Broadcast odometry TF	-> ENABLED
[ INFO] [1649853414.053647500]:  * Broadcast map pose TF	-> ENABLED
[ INFO] [1649853414.054012977]:  * Broadcast IMU pose TF	-> ENABLED
[ INFO] [1649853414.054082901]: *** DYNAMIC PARAMETERS (Init. values) ***
[ INFO] [1649853414.054301410]:  * [DYN] Depth confidence	-> 50
[ INFO] [1649853414.054501312]:  * [DYN] Depth texture conf.	-> 100
[ INFO] [1649853414.054712589]:  * [DYN] pub_frame_rate		-> 100 Hz
[ INFO] [1649853414.054921327]:  * [DYN] point_cloud_freq	-> 100 Hz
[ INFO] [1649853414.055122075]:  * [DYN] brightness		-> 4
[ INFO] [1649853414.055333617]:  * [DYN] contrast		-> 4
[ INFO] [1649853414.055609421]:  * [DYN] hue			-> 0
[ INFO] [1649853414.055882723]:  * [DYN] saturation		-> 4
[ INFO] [1649853414.056279811]:  * [DYN] sharpness		-> 4
[ INFO] [1649853414.056722737]:  * [DYN] gamma			-> 8
[ INFO] [1649853414.057146236]:  * [DYN] auto_exposure_gain	-> ENABLED
[ INFO] [1649853414.057767739]:  * [DYN] auto_whitebalance	-> ENABLED
[ INFO] [1649853414.058029578]: Openni depth mode activated -> Units: mm, Encoding: TYPE_16UC1
[ INFO] [1649853414.061529406]:  * Camera coordinate system	-> Right HANDED Z UP and X FORWARD
[ INFO] [1649853414.061637865]:  *** Opening ZED 2...
Starting OpenPose Python Wrapper...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
[INFO] [1649853414.559253]: Node Initialized
[INFO] [1649853414.559843]: Started
[ INFO] [1649853415.549963129]: ZED connection -> SUCCESS
[ INFO] [1649853417.550171903]:  ...  ZED ready
[ INFO] [1649853417.550196603]: ZED SDK running on GPU #0
[ INFO] [1649853417.559885909]: Camera-IMU Transform: 
 556E2ACD1980
0.999979 0.006302 -0.001330 -0.002000
-0.006305 0.999978 -0.001866 -0.023000
0.001318 0.001875 0.999997 0.000220
0.000000 0.000000 0.000000 1.000000

[ INFO] [1649853417.559901641]:  * CAMERA MODEL	 -> ZED 2
[ INFO] [1649853417.559913202]:  * Serial Number -> 22062221
[ INFO] [1649853417.559922341]:  * Camera FW Version -> 1523
[ INFO] [1649853417.559930773]:  * Sensors FW Version -> 776
[ INFO] [1649853417.626912034]: Advertised on topic /zed2/zed_node/rgb/image_rect_color
[ INFO] [1649853417.626958356]: Advertised on topic /zed2/zed_node/rgb/camera_info
[ INFO] [1649853417.638449095]: Advertised on topic /zed2/zed_node/rgb_raw/image_raw_color
[ INFO] [1649853417.638478127]: Advertised on topic /zed2/zed_node/rgb_raw/camera_info
[ INFO] [1649853417.650570296]: Advertised on topic /zed2/zed_node/left/image_rect_color
[ INFO] [1649853417.650595465]: Advertised on topic /zed2/zed_node/left/camera_info
[ INFO] [1649853417.662077449]: Advertised on topic /zed2/zed_node/left_raw/image_raw_color
[ INFO] [1649853417.662105514]: Advertised on topic /zed2/zed_node/left_raw/camera_info
[ INFO] [1649853417.674054862]: Advertised on topic /zed2/zed_node/right/image_rect_color
[ INFO] [1649853417.674084535]: Advertised on topic /zed2/zed_node/right/camera_info
[ INFO] [1649853417.681926422]: Advertised on topic /zed2/zed_node/right_raw/image_raw_color
[ INFO] [1649853417.681949939]: Advertised on topic /zed2/zed_node/right_raw/camera_info
[ INFO] [1649853417.689029533]: Advertised on topic /zed2/zed_node/rgb/image_rect_gray
[ INFO] [1649853417.689047035]: Advertised on topic /zed2/zed_node/rgb/camera_info
[ INFO] [1649853417.696095540]: Advertised on topic /zed2/zed_node/rgb_raw/image_raw_gray
[ INFO] [1649853417.696115671]: Advertised on topic /zed2/zed_node/rgb_raw/camera_info
[ INFO] [1649853417.703555725]: Advertised on topic /zed2/zed_node/left/image_rect_gray
[ INFO] [1649853417.703583958]: Advertised on topic /zed2/zed_node/left/camera_info
[ INFO] [1649853417.710428691]: Advertised on topic /zed2/zed_node/left_raw/image_raw_gray
[ INFO] [1649853417.710449981]: Advertised on topic /zed2/zed_node/left_raw/camera_info
[ INFO] [1649853417.718357249]: Advertised on topic /zed2/zed_node/right/image_rect_gray
[ INFO] [1649853417.718385416]: Advertised on topic /zed2/zed_node/right/camera_info
[ INFO] [1649853417.725379242]: Advertised on topic /zed2/zed_node/right_raw/image_raw_gray
[ INFO] [1649853417.725403993]: Advertised on topic /zed2/zed_node/right_raw/camera_info
[ INFO] [1649853417.732997121]: Advertised on topic /zed2/zed_node/depth/depth_registered
[ INFO] [1649853417.733034508]: Advertised on topic /zed2/zed_node/depth/camera_info
[ INFO] [1649853417.739795380]: Advertised on topic /zed2/zed_node/stereo/image_rect_color
[ INFO] [1649853417.746491963]: Advertised on topic /zed2/zed_node/stereo_raw/image_raw_color
[ INFO] [1649853417.746702403]: Advertised on topic /zed2/zed_node/confidence/confidence_map
[ INFO] [1649853417.746961620]: Advertised on topic /zed2/zed_node/disparity/disparity_image
[ INFO] [1649853417.747194221]: Advertised on topic /zed2/zed_node/point_cloud/cloud_registered
[ INFO] [1649853417.747426923]: Advertised on topic /zed2/zed_node/pose
[ INFO] [1649853417.747643387]: Advertised on topic /zed2/zed_node/pose_with_covariance
[ INFO] [1649853417.747859201]: Advertised on topic /zed2/zed_node/odom
[ INFO] [1649853417.748074305]: Advertised on topic /zed2/zed_node/path_odom
[ INFO] [1649853417.748278344]: Advertised on topic /zed2/zed_node/path_map
[ INFO] [1649853417.748524621]: Advertised on topic /zed2/zed_node/imu/data
[ INFO] [1649853417.748723584]: Advertised on topic /zed2/zed_node/imu/data_raw
[ INFO] [1649853417.748960418]: Advertised on topic /zed2/zed_node/imu/mag
[ INFO] [1649853417.749170652]: Advertised on topic /zed2/zed_node/temperature/imu
[ INFO] [1649853417.749377043]: Advertised on topic /zed2/zed_node/atm_press
[ INFO] [1649853417.749580722]: Advertised on topic /zed2/zed_node/temperature/left
[ INFO] [1649853417.749765227]: Advertised on topic /zed2/zed_node/temperature/right
[ INFO] [1649853417.749985530]: Advertised on topic /zed2/zed_node/left_cam_imu_transform [LATCHED]
[ INFO] [1649853417.751877495]: Published static transform 'zed2_imu_link' -> 'zed2_left_camera_frame'
[ INFO] [1649853417.752675049]: *** Starting Positional Tracking ***
[ INFO] [1649853417.752698187]:  * Waiting for valid static transformations...
[ INFO] [1649853417.752755762]: Static transform Sensor to Base [zed2_left_camera_frame -> base_link]
[ INFO] [1649853417.752771770]:  * Translation: {0.000,-0.060,0.000}
[ INFO] [1649853417.752786160]:  * Rotation: {0.000,-0.000,0.000}
[ INFO] [1649853417.752806949]: Static transform Sensor to Camera Center [zed2_left_camera_frame -> zed2_camera_center]
[ INFO] [1649853417.752824077]:  * Translation: {0.000,-0.060,0.000}
[ INFO] [1649853417.752848295]:  * Rotation: {0.000,-0.000,0.000}
[ INFO] [1649853417.752875310]: Static transform Camera Center to Base [zed2_camera_center -> base_link]
[ INFO] [1649853417.752891062]:  * Translation: {0.000,0.000,0.000}
[ INFO] [1649853417.752912857]:  * Rotation: {0.000,-0.000,0.000}
[ INFO] [1649853417.853025242]: Initial ZED left camera pose (ZED pos. tracking): 
[ INFO] [1649853417.853086771]:  * T: [0,0.06,0]
[ INFO] [1649853417.853099107]:  * Q: [0,0,0,1]
[ WARN] [1649853417.853141856]: area_memory_db_path [/home/aswin/.ros/zed_area_memory.area] doesn't exist or is unreachable. 
[ INFO] [1649853418.028469968]: Positional tracking -> Searching for a known position [SEARCHING]
[ INFO] [1649853418.028535316]: Odometry aligned to last tracking pose
[ INFO] [1649853418.040120201]: Positional tracking -> OK [OK]

Thanks
Please let me know if you need more info

**Comment by ravijo** [comment]
@AswinkarthikeyenAK 

>  however, there is no skeleton visible in RViz.

- Please make sure the camera is providing depth image
- Please check the depth values. I hope you are receiving depth values in millimeters or meters.
- Please print joint values using the following command:
    ```
    rostopic echo /frame
    ```

Hope it helps!

**Comment by AswinkarthikeyenAK** [comment]
Hi @ravijo ,
Thanks. 
I check the points you have pointed out. 
I tried to add a print statement in the echo, and it did not get to the script. Openpose seems to work with the ZED2 camera. but for some reason when trying to launch using zed it isn't displaying anything or opening openpose for instance. I also tested with Azure, and seems to be fine. 

Thanks

**Comment by ruksen25** [comment]
Hi @AswinkarthikeyenAK 

Has your issue been resolved? 

Otherwise I have a suspicion that the problem is that Stereolabs have changed the name of the depth topic published when the openni mode is used. 

Try to change the depth_topic parameter in the config_zed2.launch file to depth_registered. 


Thus, change it from: 

 <arg name="depth_topic" default="/zed2/zed_node/depth/depth_raw_registered" />

to 

 <arg name="depth_topic" default="/zed2/zed_node/depth/depth_registered" />



If this tip solves your issue, please let us know. Then @ravijo can update the launch file. 

Best regards
