### ISSUE TITLE
Error running the launch file run.launch

### ISSUE THREAD

**Issue by prajval10** [ravijo/ros_openpose#90]
Thanks @ravijo for the great package. The package installs correctly using `catkin_make`. I modified the launch file according to the documentation in the README. However while running the launch file, I have the following error:

```[console]
ros-workspace/devel/lib/ros_openpose/rosOpenposeAsync: symbol lookup error: ros-workspace/devel/lib/ros_openpose/rosOpenposeAsync: undefined symbol: _ZN2op17WrapperStructPoseC1ENS_8PoseModeERKNS_5PointIiEES5_NS_9ScaleModeEiiifNS_10RenderModeENS_9PoseModelEbffiRKNS_6StringERKSt6vectorINS_11HeatMapTypeESaISD_EES6_bfibdSB_SB_fb
```

**Comment by ravijo** [comment]
It seems that either the linker cannot find the correct symbol table or the symbols are not matching with the version you have.

Can you please make sure the OpenPose is installed correctly? In your OpenPose installation, you may want to execute the following commands:

```
$ git checkout tags/v1.7.0
$ make -j`nproc`
$ sudo make install
```

Later, please clean and recompile your ROS workspace's build folder.
